import type { Meal, SubscriptionPlan } from './types';

export const meals: Meal[] = [
  // --- KAHVALTI ---
  {
    id: 'k1',
    name: 'Avokado Poşe Yumurta Tost',
    enName: 'Avocado Poached Egg Toast',
    ruName: 'Тост с авокадо и яйцом пашот',
    description: 'Yumurta, labne, avokado püresi, roka, maydanoz, kişniş, yeşil zeytin, ekşi maya ekmek',
    enDescription: 'Egg, labneh, avocado puree, arugula, parsley, coriander, green olives, sourdough bread',
    ruDescription: 'Яйцо, лабне, пюре из авокадо, руккола, петрушка, кориандр, зеленые оливки, хлеб на закваске',
    category: 'kahvalti',
    imageUrl: 'https://foodforfitofficial.com/storage/27/1652278561.jpg',
    price: 575,
    calories: 306,
    protein: 20,
    carbs: 23,
    fat: 14,
    tags: ['vejetaryen'],
    available: true,
    featured: true,
  },
  {
    id: 'k2',
    name: 'Hollandez Soslu & Mantarlı Poşe Yumurta',
    enName: 'Poached Egg with Hollandaise & Mushroom',
    ruName: 'Яйцо пашот с голландским соусом и грибами',
    description: 'Yumurta, labne, avokado püresi, mantar, bernez sos, roka, maydanoz, kişniş, yeşil zeytin, ekşi maya ekmek',
    enDescription: 'Egg, labneh, avocado puree, mushroom, bearnaise sauce, arugula, parsley, coriander, green olives, sourdough bread',
    ruDescription: 'Яйцо, лабне, пюре из авокадо, грибы, беарнский соус, руккола, петрушка, кориандр, зеленые оливки, хлеб на закваске',
    category: 'kahvalti',
    imageUrl: 'https://foodforfitofficial.com/storage/255/1730966418.jpg',
    price: 600,
    calories: 729,
    protein: 27,
    carbs: 12,
    fat: 35,
    tags: ['vejetaryen'],
    available: true,
    featured: false,
  },
  {
    id: 'k3',
    name: 'Çırpılmış Yumurta',
    enName: 'Scrambled Eggs',
    ruName: 'Яичница-болтунья',
    description: 'Yumurta, süt, avokado püre, domates, kapya biber, roka, maydanoz, yeşil zeytin, kişniş, ekşi maya ekmek',
    enDescription: 'Egg, milk, avocado puree, tomato, capia pepper, arugula, parsley, green olives, coriander, sourdough bread',
    ruDescription: 'Яйцо, молоко, пюре из авокадо, помидор, перец капия, руккола, петрушка, зеленые оливки, кориандр, хлеб на закваске',
    category: 'kahvalti',
    imageUrl: 'https://foodforfitofficial.com/storage/249/1730879633.jpg',
    price: 550,
    calories: 353,
    protein: 33,
    carbs: 22,
    fat: 14,
    tags: ['yuksek-protein'],
    available: true,
    featured: true,
  },
  {
    id: 'k4',
    name: 'Hellimli Omlet',
    enName: 'Halloumi Omelette',
    ruName: 'Омлет с халуми',
    description: 'Yumurta, süt, hellim, kaşar, roka, maydanoz, kişniş, yeşil zeytin, ekşi maya ekmek',
    enDescription: 'Egg, milk, halloumi, kashkaval, arugula, parsley, coriander, green olives, sourdough bread',
    ruDescription: 'Яйцо, молоко, халуми, кашкавал, руккола, петрушка, кориандр, зеленые оливки, хлеб на закваске',
    category: 'kahvalti',
    imageUrl: 'https://foodforfitofficial.com/storage/245/1729454850.jpg',
    price: 550,
    calories: 349,
    protein: 25,
    carbs: 22,
    fat: 18,
    tags: ['vejetaryen'],
    available: true,
    featured: false,
  },
  {
    id: 'k5',
    name: 'Hindi Fümeli Tost',
    enName: 'Smoked Turkey Toast',
    ruName: 'Тост с копчёной индейкой',
    description: 'Hindi füme, kaşar, ballı hardal, light mayonez, roka, maydanoz, kişniş, yeşil zeytin, tam buğday tost ekmeği',
    enDescription: 'Smoked turkey, kashkaval, honey mustard, light mayo, arugula, parsley, coriander, green olives, whole wheat toast',
    ruDescription: 'Копчёная индейка, кашкавал, медовая горчица, лёгкий майонез, руккола, петрушка, кориандр, зеленые оливки, цельнозерновой тост',
    category: 'kahvalti',
    imageUrl: 'https://foodforfitofficial.com/storage/30/1652355147.jpg',
    price: 550,
    calories: 420,
    protein: 35,
    carbs: 41,
    fat: 13,
    tags: ['yuksek-protein'],
    available: true,
    featured: false,
  },

  // --- ANA ÖĞÜN ---
  {
    id: 'a1',
    name: '14. DETOKS TAVUK',
    enName: '14. Detox Chicken',
    ruName: '14. Детокс Курица',
    description: 'Detoks tavuk, tam buğday lavaş, fırınlanmış patates cipsi, buharda brokoli, chili sos',
    enDescription: 'Detox chicken, whole wheat lavash, baked potato chips, steamed broccoli, chili sauce',
    ruDescription: 'Детокс курица, цельнозерновой лаваш, запеченные картофельные чипсы, брокколи на пару, соус чили',
    category: 'ana',
    imageUrl: 'https://foodforfitofficial.com/storage/44/1652443929.jpg',
    price: 880,
    calories: 639,
    protein: 61,
    carbs: 30,
    fat: 30,
    tags: ['yuksek-protein', 'detoks'],
    available: true,
    featured: true,
  },
  {
    id: 'a2',
    name: '13. BALLI & HARDALLI TAVUK',
    enName: '13. Honey & Mustard Chicken',
    ruName: '13. Курица в медово-горчичном соусе',
    description: 'Ballı & hardallı tavuk, fırınlanmış patates cipsi, mevsim yeşillikleri, ballı & hardallı sos',
    enDescription: 'Honey & mustard chicken, baked potato chips, seasonal greens, honey & mustard sauce',
    ruDescription: 'Курица в медово-горчичном соусе, запеченные чипсы, сезонная зелень, медово-горчичный соус',
    category: 'ana',
    imageUrl: 'https://foodforfitofficial.com/storage/45/1652444994.jpg',
    price: 860,
    calories: 492,
    protein: 45,
    carbs: 39,
    fat: 17,
    tags: ['yuksek-protein'],
    available: true,
    featured: true,
  },
  {
    id: 'a3',
    name: '16. ACILI TAVUK',
    enName: '16. Spicy Chicken',
    ruName: '16. Острая курица',
    description: 'Özel sosla harmanlanmış acılı tavuk, fırınlanmış patates cipsi, mevsim yeşillikleri',
    enDescription: 'Spicy chicken with special sauce, baked potato chips, seasonal greens',
    ruDescription: 'Острая курица в фирменном соусе, запеченные чипсы, сезонная зелень',
    category: 'ana',
    imageUrl: 'https://foodforfitofficial.com/storage/46/1652445191.jpg',
    price: 810,
    calories: 407,
    protein: 46,
    carbs: 21,
    fat: 15,
    tags: ['yuksek-protein'],
    available: true,
    featured: false,
  },
  {
    id: 'a4',
    name: '15. SADE TAVUK',
    enName: '15. Plain Chicken',
    ruName: '15. Куриная грудка',
    description: 'Sade tavuk, pirinç pilavı, salata',
    enDescription: 'Plain chicken, rice pilaf, salad',
    ruDescription: 'Куриная грудка, рисовый плов, салат',
    category: 'ana',
    imageUrl: 'https://foodforfitofficial.com/storage/49/1652446126.jpg',
    price: 810,
    calories: 514,
    protein: 47,
    carbs: 51,
    fat: 13,
    tags: ['yuksek-protein'],
    available: true,
    featured: false,
  },
  {
    id: 'a5',
    name: '21. HELLİMLİ & PEYNİRLİ TAVUK SARMA',
    enName: '21. Halloumi & Cheese Chicken Wrap',
    ruName: '21. Куриный рулет с халуми и сыром',
    description: 'Tavuk sarma, haşlanmış brokoli, salata',
    enDescription: 'Chicken wrap, boiled broccoli, salad',
    ruDescription: 'Куриный рулет, отварная брокколи, салат',
    category: 'ana',
    imageUrl: 'https://foodforfitofficial.com/storage/224/1688713698.jpg',
    price: 890,
    calories: 421,
    protein: 57,
    carbs: 30,
    fat: 8,
    tags: ['yuksek-protein'],
    available: true,
    featured: true,
  },
  {
    id: 'a6',
    name: '38. IZGARA SOMON',
    enName: '38. Grilled Salmon',
    ruName: '38. Лосось на гриле',
    description: 'Izgara somon, fırın patates, salata ve pancar sos',
    enDescription: 'Grilled salmon, baked potato, salad and beetroot sauce',
    ruDescription: 'Лосось на гриле, запеченный картофель, салат и свекольный соус',
    category: 'ana',
    imageUrl: 'https://foodforfitofficial.com/storage/248/1729455538.jpg',
    price: 1200,
    calories: 345,
    protein: 26,
    carbs: 33,
    fat: 12,
    tags: ['omega-3', 'yuksek-protein'],
    available: true,
    featured: true,
  },
  {
    id: 'a7',
    name: '32. SEBZELİ MUSAKKA',
    enName: '32. Vegetable Moussaka',
    ruName: '32. Овощная мусака',
    description: 'Közlenmiş patlıcan, patates, mercimek bolognese üzeri, kaju ekşi krema ve parmezan, salata',
    enDescription: 'Roasted eggplant, potato, lentil bolognese, cashew sour cream and parmesan, salad',
    ruDescription: 'Запечённый баклажан, картофель, чечевичный болоньезе, кешью сметана и пармезан, салат',
    category: 'ana',
    imageUrl: 'https://foodforfitofficial.com/storage/176/1654766304.jpg',
    price: 700,
    calories: 602,
    protein: 23,
    carbs: 51,
    fat: 34,
    tags: ['vejetaryen'],
    available: true,
    featured: false,
  },
  {
    id: 'a8',
    name: '12. ETLİ KURU FASULYE',
    enName: '12. Meat & Bean Stew',
    ruName: '12. Фасоль с мясом',
    description: 'Etli kuru fasulye, pirinç pilavı, salata',
    enDescription: 'Meat and white bean stew, rice pilaf, salad',
    ruDescription: 'Рагу из белой фасоли с мясом, рисовый плов, салат',
    category: 'ana',
    imageUrl: '',
    price: 810,
    calories: 453,
    protein: 35,
    carbs: 40,
    fat: 15,
    tags: ['geleneksel'],
    available: true,
    featured: false,
  },
  {
    id: 'a9',
    name: 'GYM MENÜ (Kıyma & Pilav)',
    enName: 'GYM MENU (Minced Meat & Rice)',
    ruName: 'GYM МЕНЮ (Фарш и рис)',
    description: 'Pilav üstünde kıyma ve yanında salata ile',
    enDescription: 'Minced meat over rice with side salad',
    ruDescription: 'Фарш на рисе с гарниром из салата',
    category: 'ana',
    imageUrl: 'https://foodforfitofficial.com/storage/233/1702375442.jpg',
    price: 1100,
    calories: 550,
    protein: 41,
    carbs: 60,
    fat: 18,
    tags: ['yuksek-protein', 'gym'],
    available: true,
    featured: true,
  },

  // --- KASE & SALATA ---
  {
    id: 's1',
    name: '17. Tavuk Avokado Salata',
    enName: '17. Chicken Avocado Salad',
    ruName: '17. Салат с курицей и авокадо',
    description: 'Sade tavuk, avokado, mevsim yeşillikleri, domates, salatalık',
    enDescription: 'Plain chicken, avocado, seasonal greens, tomato, cucumber',
    ruDescription: 'Куриная грудка, авокадо, сезонная зелень, помидор, огурец',
    category: 'kase',
    imageUrl: 'https://foodforfitofficial.com/storage/26/1652277731.jpg',
    price: 700,
    calories: 258,
    protein: 31,
    carbs: 5,
    fat: 12,
    tags: ['yuksek-protein', 'dusuk-karbonhidrat'],
    available: true,
    featured: true,
  },
  {
    id: 's2',
    name: '37. Izgara Somon Salata',
    enName: '37. Grilled Salmon Salad',
    ruName: '37. Салат с лососем на гриле',
    description: 'Izgara somon, avokado, beyaz peynir, ceviz, mevsim yeşillikleri ve zeytinyağlı sos',
    enDescription: 'Grilled salmon, avocado, white cheese, walnuts, seasonal greens and olive oil dressing',
    ruDescription: 'Лосось на гриле, авокадо, белый сыр, грецкие орехи, сезонная зелень и заправка из оливкового масла',
    category: 'kase',
    imageUrl: 'https://foodforfitofficial.com/storage/62/1652516019.jpg',
    price: 1150,
    calories: 478,
    protein: 44,
    carbs: 6,
    fat: 41,
    tags: ['omega-3', 'zengin-yag'],
    available: true,
    featured: false,
  },
  {
    id: 's3',
    name: 'Detoks Tavuk Kase',
    enName: 'Detox Chicken Bowl',
    ruName: 'Детокс-боул с курицей',
    description: 'Detoks tavuk, buharda pilav, buharda brokoli, chili sos',
    enDescription: 'Detox chicken, steamed rice, steamed broccoli, chili sauce',
    ruDescription: 'Детокс курица, рис на пару, брокколи на пару, соус чили',
    category: 'kase',
    imageUrl: 'https://foodforfitofficial.com/storage/70/1652532820.jpg',
    price: 790,
    calories: 748,
    protein: 48,
    carbs: 66,
    fat: 31,
    tags: ['yuksek-protein'],
    available: true,
    featured: false,
  },
  {
    id: 's4',
    name: '35. Rainbowl Mix',
    enName: '35. Rainbow Bowl Mix',
    ruName: '35. Радужный микс-боул',
    description: 'Felafel, mücver, tofu, mantar, buharda pilav, buharda karışık sebze, tahin sos',
    enDescription: 'Falafel, vegetable fritter, tofu, mushroom, steamed rice, steamed mixed vegetables, tahini sauce',
    ruDescription: 'Фалафель, овощные оладьи, тофу, грибы, рис на пару, паровые овощи, тахинный соус',
    category: 'kase',
    imageUrl: 'https://foodforfitofficial.com/storage/97/1652689972.jpg',
    price: 760,
    calories: 536,
    protein: 24,
    carbs: 82,
    fat: 12,
    tags: ['vegan', 'vejetaryen'],
    available: true,
    featured: true,
  },

  // --- SMOOTHIE & JUICE ---
  {
    id: 'd1',
    name: 'Acai Berry Smoothie',
    enName: 'Acai Berry Smoothie',
    ruName: 'Смузи с асаи',
    description: 'Muz, böğürtlen, badem, bal, süt',
    enDescription: 'Banana, blackberry, almond, honey, milk',
    ruDescription: 'Банан, ежевика, миндаль, мёд, молоко',
    category: 'smoothie',
    imageUrl: '',
    price: 440,
    calories: 250,
    protein: 6,
    carbs: 45,
    fat: 8,
    tags: ['antioksidan'],
    available: true,
    featured: true,
  },
  {
    id: 'd2',
    name: 'Fat Burner Juice',
    enName: 'Fat Burner Juice',
    ruName: 'Жиросжигающий сок',
    description: 'Zencefil, limon, yeşil elma, ananas',
    enDescription: 'Ginger, lemon, green apple, pineapple',
    ruDescription: 'Имбирь, лимон, зелёное яблоко, ананас',
    category: 'smoothie',
    imageUrl: '',
    price: 460,
    calories: 120,
    protein: 2,
    carbs: 28,
    fat: 0,
    tags: ['detoks', 'yag-yakici'],
    available: true,
    featured: true,
  },
  {
    id: 'd3',
    name: 'Fresh Orange',
    enName: 'Fresh Orange Juice',
    ruName: 'Свежевыжатый апельсиновый сок',
    description: 'Sade portakal suyu, isteğe göre taze zencefil',
    enDescription: 'Fresh orange juice, optional fresh ginger',
    ruDescription: 'Свежевыжатый апельсиновый сок, по желанию свежий имбирь',
    category: 'smoothie',
    imageUrl: '',
    price: 300,
    calories: 180,
    protein: 3,
    carbs: 40,
    fat: 1,
    tags: ['vitamin-c'],
    available: true,
    featured: false,
  },

  // --- TATLI (Sugar Free) ---
  {
    id: 't1',
    name: 'Şekersiz Tiramisu',
    enName: 'Sugar-Free Tiramisu',
    ruName: 'Тирамису без сахара',
    description: 'FoodForFit özel tarifli, şeker ilavesiz hafif tiramisu',
    enDescription: 'FoodForFit special recipe, light tiramisu with no added sugar',
    ruDescription: 'Фирменный рецепт FoodForFit, лёгкое тирамису без добавления сахара',
    category: 'tatli',
    imageUrl: '',
    price: 380,
    calories: 210,
    protein: 12,
    carbs: 18,
    fat: 10,
    tags: ['sekersiz'],
    available: true,
    featured: true,
  },
  {
    id: 't2',
    name: 'Böğürtlenli Cheesecake',
    enName: 'Blackberry Cheesecake',
    ruName: 'Чизкейк с ежевикой',
    description: 'Şeker ilavesiz, taze böğürtlen soslu hafif cheesecake',
    enDescription: 'No added sugar, light cheesecake with fresh blackberry sauce',
    ruDescription: 'Без добавления сахара, лёгкий чизкейк со свежим ежевичным соусом',
    category: 'tatli',
    imageUrl: '',
    price: 320,
    calories: 240,
    protein: 10,
    carbs: 20,
    fat: 14,
    tags: ['sekersiz'],
    available: true,
    featured: true,
  },
];

export const subscriptionPlans: SubscriptionPlan[] = [
  {
    id: 'plan-14',
    name: '14 Öğün Paketi',
    enName: '14 Meals Package',
    ruName: 'Пакет 14 блюд',
    mealCount: 14,
    price: 6500,
    pricePerMeal: 464,
    features: ['Ücretsiz Teslimat', 'Makro Takibi', 'Esnek Menü', 'Haftalık Değişen Menü'],
    enFeatures: ['Free Delivery', 'Macro Tracking', 'Flexible Menu', 'Weekly Menu Changes'],
    ruFeatures: ['Бесплатная доставка', 'Отслеживание макросов', 'Гибкое меню', 'Еженедельное меню'],
    badge: 'En Popüler',
    enBadge: 'Most Popular',
    ruBadge: 'Самый популярный',
    popular: true,
    allowedMealIds: [],
  },
  {
    id: 'plan-21',
    name: '21 Öğün Paketi',
    enName: '21 Meals Package',
    ruName: 'Пакет 21 блюдо',
    mealCount: 21,
    price: 9450,
    pricePerMeal: 450,
    features: ['Ücretsiz Teslimat', 'Makro Takibi', 'Esnek Menü', 'Haftalık Değişen Menü', 'Diyetisyen Desteği'],
    enFeatures: ['Free Delivery', 'Macro Tracking', 'Flexible Menu', 'Weekly Menu Changes', 'Dietitian Support'],
    ruFeatures: ['Бесплатная доставка', 'Отслеживание макросов', 'Гибкое меню', 'Еженедельное меню', 'Поддержка диетолога'],
    badge: 'En Uygun',
    enBadge: 'Best Value',
    ruBadge: 'Лучшая цена',
    popular: false,
    allowedMealIds: [],
  },
  {
    id: 'plan-28',
    name: '28 Öğün Paketi',
    enName: '28 Meals Package',
    ruName: 'Пакет 28 блюд',
    mealCount: 28,
    price: 12000,
    pricePerMeal: 429,
    features: ['Ücretsiz Teslimat', 'Makro Takibi', 'Esnek Menü', 'Haftalık Değişen Menü', 'Diyetisyen Desteği', 'Öncelikli Teslimat'],
    enFeatures: ['Free Delivery', 'Macro Tracking', 'Flexible Menu', 'Weekly Menu Changes', 'Dietitian Support', 'Priority Delivery'],
    ruFeatures: ['Бесплатная доставка', 'Отслеживание макросов', 'Гибкое меню', 'Еженедельное меню', 'Поддержка диетолога', 'Приоритетная доставка'],
    popular: false,
    allowedMealIds: [],
  },
];

export const categories = [
  { key: 'all', label: 'Tüm Menü', enLabel: 'Full Menu', ruLabel: 'Всё меню', emoji: '🍽️' },
  { key: 'kahvalti', label: 'Kahvaltılar', enLabel: 'Breakfast', ruLabel: 'Завтраки', emoji: '🍳' },
  { key: 'ana', label: 'Ana Öğünler', enLabel: 'Main Courses', ruLabel: 'Основные блюда', emoji: '🥩' },
  { key: 'kase', label: 'Kaseler & Salatalar', enLabel: 'Bowls & Salads', ruLabel: 'Боулы и салаты', emoji: '🥗' },
  { key: 'smoothie', label: "İçecekler", enLabel: 'Drinks', ruLabel: 'Напитки', emoji: '🥤' },
  { key: 'tatli', label: "Şekersiz Tatlılar", enLabel: 'Sugar-Free Desserts', ruLabel: 'Десерты без сахара', emoji: '🍰' },
];

export const tagOptions = [
  { key: 'vejetaryen', label: 'Vejetaryen', enLabel: 'Vegetarian', ruLabel: 'Вегетарианское' },
  { key: 'vegan', label: 'Vegan', enLabel: 'Vegan', ruLabel: 'Веганское' },
  { key: 'yuksek-protein', label: 'Yüksek Protein', enLabel: 'High Protein', ruLabel: 'Высокий белок' },
  { key: 'sekersiz', label: 'Şekersiz', enLabel: 'Sugar-Free', ruLabel: 'Без сахара' },
  { key: 'omega-3', label: 'Omega-3', enLabel: 'Omega-3', ruLabel: 'Омега-3' },
  { key: 'detoks', label: 'Detoks', enLabel: 'Detox', ruLabel: 'Детокс' },
];

export function getMealGradient(meal: Meal): string {
  switch (meal.category) {
    case 'kahvalti':
      return 'linear-gradient(135deg, #FDE68A 0%, #F59E0B 100%)';
    case 'ana':
      return 'linear-gradient(135deg, #6EE7B7 0%, #10B981 100%)';
    case 'kase':
      return 'linear-gradient(135deg, #93C5FD 0%, #3B82F6 100%)';
    case 'smoothie':
      return 'linear-gradient(135deg, #C4B5FD 0%, #8B5CF6 100%)';
    case 'tatli':
      return 'linear-gradient(135deg, #F9A8D4 0%, #EC4899 100%)';
    default:
      return 'linear-gradient(135deg, #E5E7EB 0%, #9CA3AF 100%)';
  }
}

export function getMealEmoji(meal: Meal): string {
  switch (meal.category) {
    case 'kahvalti': return '🍳';
    case 'ana': return '🍲';
    case 'kase': return '🥗';
    case 'smoothie': return '🥤';
    case 'tatli': return '🍰';
    default: return '🥘';
  }
}
