import type { Meal, SubscriptionPlan } from './types';

export const meals: Meal[] = [
  {
    id: '1',
    name: 'Avokado Poşe Yumurta Tost',
    description: 'Yumurta, labne, avokado püresi, roka, maydanoz, kişniş, yeşil zeytin, ekşi maya ekmek',
    category: 'kahvalti',
    imageUrl: '',
    price: 575,
    calories: 306,
    protein: 20,
    carbs: 23,
    fat: 14,
    tags: ['vejetaryen', 'besleyici'],
    available: true,
    featured: true,
  },
  {
    id: '2',
    name: 'Hollandez Soslu & Mantarlı Poşe Yumurta',
    description: 'Yumurta, labne, avokado püresi, mantar, bernez sos, roka, maydanoz, kişniş, yeşil zeytin, ekşi maya ekmek',
    category: 'kahvalti',
    imageUrl: '',
    price: 600,
    calories: 729,
    protein: 27,
    carbs: 12,
    fat: 35,
    tags: ['vejetaryen', 'zengin'],
    available: true,
    featured: false,
  },
  {
    id: '3',
    name: 'Çırpılmış Yumurta',
    description: 'Yumurta, süt, avokado püre, domates, kapya biber, roka, maydanoz, yeşil zeytin, kişniş, ekşi maya ekmek',
    category: 'kahvalti',
    imageUrl: '',
    price: 550,
    calories: 353,
    protein: 33,
    carbs: 22,
    fat: 14,
    tags: ['yuksek-protein'],
    available: true,
    featured: true,
  },
  {
    id: '4',
    name: 'Hellimli Omlet',
    description: 'Yumurta, süt, hellim, kaşar, roka, maydanoz, kişniş, yeşil zeytin, ekşi maya ekmek',
    category: 'kahvalti',
    imageUrl: '',
    price: 550,
    calories: 349,
    protein: 25,
    carbs: 22,
    fat: 18,
    tags: ['vejetaryen'],
    available: true,
    featured: false,
  },
  {
    id: '5',
    name: 'Hindi Fümeli Tost',
    description: 'Hindi füme, kaşar, ballı hardal, light mayonez, roka, maydanoz, kişniş, yeşil zeytin, tam buğday tost ekmeği',
    category: 'kahvalti',
    imageUrl: '',
    price: 550,
    calories: 420,
    protein: 35,
    carbs: 41,
    fat: 13,
    tags: ['yuksek-protein'],
    available: true,
    featured: true,
  },
  {
    id: '6',
    name: '14.Detoks Tavuk',
    description: 'Detoks tavuk, tam buğday lavaş, fırınlanmış patates cipsi, buharda brokoli, chili sos',
    category: 'ana',
    imageUrl: '',
    price: 880,
    calories: 639,
    protein: 61,
    carbs: 30,
    fat: 30,
    tags: ['yuksek-protein', 'detoks'],
    available: true,
    featured: true,
  },
  {
    id: '7',
    name: '13.Ballı & Hardallı Tavuk',
    description: 'Ballı & hardallı tavuk, fırınlanmış patates cipsi, mevsim yeşillikleri, ballı & hardallı sos',
    category: 'ana',
    imageUrl: '',
    price: 860,
    calories: 492,
    protein: 45,
    carbs: 39,
    fat: 17,
    tags: ['yuksek-protein'],
    available: true,
    featured: false,
  },
  {
    id: '8',
    name: '38.Izgara Somon',
    description: 'Izgara somon, fırın patates, salata ve pancar sos',
    category: 'ana',
    imageUrl: '',
    price: 1200,
    calories: 345,
    protein: 26,
    carbs: 33,
    fat: 12,
    tags: ['yuksek-protein', 'omega-3'],
    available: true,
    featured: true,
  },
  {
    id: '9',
    name: '17.Tavuk Avokado Salata',
    description: 'Sade tavuk, avokado, mevsim yeşillikleri, domates, salatalık',
    category: 'kase',
    imageUrl: '',
    price: 700,
    calories: 258,
    protein: 31,
    carbs: 5,
    fat: 12,
    tags: ['yuksek-protein', 'dusuk-karbonhidrat'],
    available: true,
    featured: false,
  },
  {
    id: '10',
    name: '37.Izgara Somon Salata',
    description: 'Izgara somon, avokado, beyaz peynir, ceviz, mevsim yeşillikleri ve zeytinyağlı sos',
    category: 'kase',
    imageUrl: '',
    price: 1150,
    calories: 478,
    protein: 44,
    carbs: 6,
    fat: 41,
    tags: ['yuksek-protein', 'zengin-yag'],
    available: true,
    featured: true,
  },
  {
    id: '11',
    name: 'Detoks Tavuk Kase',
    description: 'Detoks tavuk, buharda pilav, buharda brokoli, chili sos',
    category: 'kase',
    imageUrl: '',
    price: 790,
    calories: 748,
    protein: 48,
    carbs: 66,
    fat: 31,
    tags: ['yuksek-protein', 'doyurucu'],
    available: true,
    featured: true,
  },
  {
    id: '12',
    name: '35.Rainbowl Mix',
    description: 'Felafel, mücver, tofu, mantar, buharda pilav, buharda karışık sebze, tahin sos',
    category: 'kase',
    imageUrl: '',
    price: 760,
    calories: 536,
    protein: 24,
    carbs: 82,
    fat: 12,
    tags: ['vejetaryen', 'vegan'],
    available: true,
    featured: false,
  },
  {
    id: '13',
    name: 'Detoks Tavuk Wrap',
    description: 'Detoks tavuk. mevsim yeşillikleri, chilli sos, lavaş',
    category: 'ana',
    imageUrl: '',
    price: 380,
    calories: 583,
    protein: 43,
    carbs: 57,
    fat: 17,
    tags: ['yuksek-protein'],
    available: true,
    featured: false,
  },
  {
    id: '14',
    name: 'Acai Berry Smoothie',
    description: 'Muz, böğürtlen, badem, bal, süt',
    category: 'smoothie',
    imageUrl: '',
    price: 440,
    calories: 250,
    protein: 6,
    carbs: 45,
    fat: 8,
    tags: ['antioksidan', 'besleyici'],
    available: true,
    featured: true,
  },
  {
    id: '15',
    name: 'Strawberry Coconut Bowl',
    description: 'Muz, çilek, bal, süt, hindistancevizi kasesinde servis edilir',
    category: 'smoothie',
    imageUrl: '',
    price: 510,
    calories: 320,
    protein: 8,
    carbs: 52,
    fat: 12,
    tags: ['vejetaryen', 'taze'],
    available: true,
    featured: true,
  },
];

export const subscriptionPlans: SubscriptionPlan[] = [
  {
    id: 'plan-14',
    name: '14 Öğün Paketi',
    mealCount: 14,
    price: 6500,
    pricePerMeal: 464,
    features: ['Ücretsiz Teslimat', 'Makro Takibi', 'Esnek Menü', 'Haftalık Değişen Menü'],
    badge: 'En Popüler',
    popular: true,
    allowedMealIds: [],
  },
  {
    id: 'plan-21',
    name: '21 Öğün Paketi',
    mealCount: 21,
    price: 9450,
    pricePerMeal: 450,
    features: ['Ücretsiz Teslimat', 'Makro Takibi', 'Esnek Menü', 'Haftalık Değişen Menü', 'Diyetisyen Desteği'],
    badge: 'En Uygun',
    popular: false,
    allowedMealIds: [],
  },
  {
    id: 'plan-28',
    name: '28 Öğün Paketi',
    mealCount: 28,
    price: 12000,
    pricePerMeal: 429,
    features: ['Ücretsiz Teslimat', 'Makro Takibi', 'Esnek Menü', 'Haftalık Değişen Menü', 'Diyetisyen Desteği', 'Öncelikli Teslimat'],
    popular: false,
    allowedMealIds: [],
  },
];

export const categories = [
  { key: 'all', label: 'Tüm Menü', emoji: '🍽️' },
  { key: 'kahvalti', label: 'Kahvaltılar', emoji: '🍳' },
  { key: 'ana', label: 'Ana Öğünler', emoji: '🍲' },
  { key: 'kase', label: 'Kaseler & Salatalar', emoji: '🥗' },
  { key: 'smoothie', label: "Smoothie & Kaseler", emoji: '🥤' },
];

export const tagOptions = [
  { key: 'vejetaryen', label: 'Vejetaryen' },
  { key: 'vegan', label: 'Vegan' },
  { key: 'yuksek-protein', label: 'Yüksek Protein' },
  { key: 'besleyici', label: 'Besleyici' },
  { key: 'omega-3', label: 'Omega-3' },
];

export function getMealGradient(meal: Meal): string {
  switch (meal.category) {
    case 'kahvalti':
      return 'linear-gradient(135deg, #FDE68A 0%, #F59E0B 100%)';
    case 'ana':
      return 'linear-gradient(135deg, #6EE7B7 0%, #10B981 100%)';
    case 'kase':
      return 'linear-gradient(135deg, #93C5FD 0%, #3B82F6 100%)';
    case 'smoothie':
      return 'linear-gradient(135deg, #C4B5FD 0%, #8B5CF6 100%)';
    default:
      return 'linear-gradient(135deg, #E5E7EB 0%, #9CA3AF 100%)';
  }
}

export function getMealEmoji(meal: Meal): string {
  switch (meal.category) {
    case 'kahvalti': return '🍳';
    case 'ana': return '🍲';
    case 'kase': return '🥗';
    case 'smoothie': return '🥤';
    default: return '🥘';
  }
}
